name: Docs

on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Render terraform-docs
        uses: terraform-docs/gh-actions@v1.2.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"

